check.py script to get status on maintained domains in inventory.yaml
Current output with HEAD method, need to catch DNS error somehow:

    k8s.io <Response [302]>
    changelog.k8s.io <Response [302]>
    code.k8s.io <Response [302]>
    docs.k8s.io <Response [302]>
    examples.k8s.io <Response [302]>
    get.k8s.io <Response [200]>
    issue.k8s.io <Response [302]>
    issues.k8s.io <Response [302]>
    Traceback (most recent call last):
      File "check.py", line 11, in <module>
        status = requests.head('http://' + site)
      File "C:\Python27\lib\site-packages\requests\api.py", line 93, in head
        return request('head', url, **kwargs)
      File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
        return session.request(method=method, url=url, **kwargs)
      File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "C:\Python27\lib\site-packages\requests\adapters.py", line 437, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='jenkins.k8s.io', port=80):
        Max retries exceeded with url: / (Caused by
        NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at
        0x029E43B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Roadmap:

* [ ] catch missing/expired DNS records
  * [ ] generate signal (fedmsg?)
* [ ] follow redirects
  * [ ] show redirects
  * [ ] configure redirects from inventory.yaml
* [ ] check https availability
  * [ ] check http and https content matches (or redirects)